export const QUESTIONS: string[] = [
  "Findet man in der Küche",
  "Braucht man zum Kochen",
  "Ist essbar",
  "Ist ein Gewürz",
  "Ist ein Küchengerät",
  "Ist etwas Süßes",
  "Ist ein Getränk",
  "Ist im Kühlschrank",
  "Benutzt man zum Backen",
  "Ist ein Obst",
  "Ist ein Gemüse",
  "Findet man im Wohnzimmer",
  "Steht im Schlafzimmer",
  "Ist im Badezimmer",
  "Hängt an der Wand",
  "Ist aus Holz",
  "Ist weich",
  "Ist aus Glas",
  "Ist eine Stadt",
  "Ist ein Land",
  "Ist ein Beruf",
  "Ist ein Tier",
  "Ist ein Insekt",
  "Ist ein Vogel",
  "Ist ein Fahrzeug",
  "Kann fliegen"
];
